fenix/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from rest_framework.urlpatterns import format_suffix_patterns

from fenix import settings
from userprofile import api, views
from catalog.views import index, category, view_details, expres_save, search_key, view_expresfile, download_link, \
    download_d, myfiles, private_files, addfile, get_addfile, view_details_slug, search

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # Home
    url(r'^$', index, name='home'),

    # SignUp
    url(r'^signup/$', views.signup, name='signup'),

    # SignIn
    url(r'^signin/$', views.signin, name='signin'),

    # SignOut
    url(r'^signout/$', views.signout, name='signout'),

    # Profile
    url(r'^user-(?P<user_id>\d+)/$', views.profile, name='user_profile'),
    url(r'^user-(?P<user_id>\d+)/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^user-(?P<user_id>\d+)/edit/save/$', views.edit_profile, name='edit_profile_save'),
    url(r'^user-(?P<user_id>\d+)/my-files/$', myfiles, name='myfiles'),
    url(r'^user-(?P<user_id>\d+)/private-files/$', private_files, name='private_files'),
    url(r'addfiles/$', addfile, name='addfiles'),
    url(r'^addfiles/add$', get_addfile, name='add'),

    # Details
    url(r'^view-(?P<slug>[\w-]+)/$', view_details, name='details'),
    url(r'^view-(?P<slug>[\w-]+)/download/(?P<file_id>\d+)/$', download_d, name='download_d' ),
    url(r'^slug-(?P<slug>[\w-]+)/$', view_details_slug, name='details_slug'),

    #
    url(r'^addfile/new/$', expres_save, name='addfile'),
    #
    url(r'^search-key/$', search_key, name='search_key' ),
    url(r'^get-(?P<slug>[\w-]+)/$', view_expresfile, name='search_Link' ),
    url(r'^get-(?P<slug>[\w-]+)/download/(?P<file_id>\d+)/$', download_link, name='download' ),

    url(r'^search/$', search, name='search'),



    # Category
    url(r'^views-(?P<category_slug>[\w-]+)/', category, name='category'),


    # API
    url(r'^api-v1.0/users/$', api.UserList.as_view()),
    url(r'^api-v1.0/user/(?P<pk>[0-9]+)/$', api.UserDetail.as_view())
]
urlpatterns = format_suffix_patterns(urlpatterns)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

catalog/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.dispatch import receiver
from django.utils.text import slugify

from fenix.settings import MEDIA_ROOT
from userprofile.models import User
from sorl.thumbnail import ImageField, get_thumbnail, fields
import datetime
from django.contrib.auth.models import UserManager


def randomStr():
    return str(datetime.datetime.now().year)+'-'+(UserManager().make_random_password(length=25))

class Category(models.Model):
    name= models.CharField(max_length=20)
    slug = models.SlugField(verbose_name='Алиас')
    is_publish = models.BooleanField(verbose_name='Опубликовать', default=False)

    class Meta:
        db_table = 'category'
        verbose_name = 'Категория'
        verbose_name_plural='Категории'

    def __str__(self):
        return self.name

def upload_cover(instance, filename):
    return u'%s/%s/%s/cover/%s' % (datetime.datetime.now().year, instance.user_id, instance.category.slug, filename)
CHOICES = [('is_open', 'Опубликован'),
           ('is_slug', 'Доступ по ссылке'),
           ('is_for_me', 'Только для меня')]
class Catalog(models.Model):
    cover = ImageField(verbose_name='Постер', upload_to=upload_cover)
    date_add = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    category = models.ForeignKey(Category, verbose_name='Категория')
    user = models.ForeignKey(User, verbose_name='Автор')
    description = models.TextField(verbose_name='Описание', max_length=300)
    slug = models.SlugField(verbose_name='Алиас', default=randomStr, unique=True)
    # is_open = models.BooleanField(verbose_name='Для всех', help_text='Дать доступ к файлу для всех пользователей')
    # is_slug = models.BooleanField(verbose_name='По ссылке', help_text='Файл будет доступен только по ссылке')
    # is_for_me = models.BooleanField(verbose_name='Только для меня', help_text='Файл будет доступен только Вам')
    choices = models.CharField(choices=CHOICES, max_length=11, verbose_name='Публикация' )

    class Meta:
        db_table = 'catalog'
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'

    def __str__(self):
        return self.title

class ExpresFiles(models.Model):
    email = models.EmailField(verbose_name='Email')
    description = models.TextField(verbose_name='Описание',max_length=300)
    slug = models.SlugField(verbose_name='Алиас', blank=True, null=True, default=randomStr, unique=True)#max_length=25
    date_add = models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')

    class Meta:
        db_table = 'expresfiles'
        verbose_name = 'Временные файлы'
        verbose_name_plural = 'Временные файлы'

    def __str__(self):
        return self.email

def upload_file_catalog(instance, filename):
    d = datetime.datetime.now()
    if instance.catalog:
        m = instance.catalog.user_id
        c = instance.catalog.slug
    else:
        m = 0
        c = 0
    return u'%s/%s/%s/%s' % (d.year, m, c, filename)

def upload_file(instance, filename):
    d = datetime.datetime.now()
    if instance.expresfile:
        m = instance.expresfile.email
        c = instance.expresfile.slug
    else:
        m = 0
        c = 0
    return u'%s/%s/%s/%s' % (d.year, m, c, filename)

class FilesCatalog(models.Model):
    catalog = models.ForeignKey(Catalog, on_delete=models.CASCADE, blank=True, null=True)
    files_s = models.FileField(verbose_name='Файл', upload_to=upload_file_catalog)

    class Meta:
        db_table = 'files_catalog'
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'
    def __str__(self):
        return str(self.files_s)

class FilesExpres(models.Model):
    expresfile = models.ForeignKey(ExpresFiles, verbose_name='Временные файлы', on_delete=models.CASCADE, blank=True, null=True)
    files_s = models.FileField(verbose_name='Файл', upload_to=upload_file)

    class Meta:
        db_table = 'files_expres'
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'

    def __str__(self):
        return str(self.files_s)

catalog/views.py
# -*- coding: utf-8 -*-
import os

from django.contrib import auth
from django.contrib import messages
from django.core.mail import send_mail
from django.http import Http404
from django.http import HttpResponse
from django.template.context_processors import csrf
from django.shortcuts import render, redirect, render_to_response

from catalog.forms import ExpresFilesForms, FilesExpresForms, TestForm, SearchForm, SearchKey, AddCatalogForm, \
    FilesCatalogForms, CatalogForms
from fenix import settings
from .models import Category, Catalog, FilesCatalog, FilesExpres, ExpresFiles

from django.contrib.auth.models import UserManager
import re
from django.db.models import Q
from django import forms

def index(request):
    args={}
    args['title'] = 'Home'
    args['catalog'] = Catalog.objects.filter(choices='is_open', category__is_publish=True).order_by('-date_add')
    args['expres_form'] = ExpresFilesForms()
    args['files_expres'] = FilesExpresForms()
    args['form_search_key'] = SearchKey()
    args['username'] = auth.get_user(request).username
    return render(request, '../templates/catalog/index.html', args)

def valid_file(self):
    file = self
    try:
        if file:
            file_type =file.content_type.split('/')[0]
            if len(str(file).split('.'))==1:
                raise forms.ValidationError('1: File type is not supported')

            if file_type not in settings.UPLOAD_FILE_TYPE:
                raise forms.ValidationError('2: File type is not supported ')
    except:
        pass

    return file

def expres_save(request):
    args={}
    return_path = request.META.get('HTTP_REFERER', '/')
    url_site = request.META['HTTP_HOST']
    args.update(csrf(request))
    args['username'] = auth.get_user(request).username
    args['expres_form'] = ExpresFilesForms()
    args['files_expres'] = FilesExpresForms()
    mes=0
    con = 0

    if request.POST and request.FILES:
        form_e = ExpresFilesForms(request.POST, request.FILES)
        form_f = FilesExpresForms(request.FILES)
        random_slug = UserManager().make_random_password(length=25)
        if form_e.is_valid():
            form_e.instance.slug = random_slug
            form_e.save()
            for count, x in enumerate(request.FILES.getlist('files_s')):
                ft = FilesExpres.objects.create(
                    expresfile=ExpresFiles.objects.get(id=form_e.instance.id),
                    files_s=valid_file(x)
                )
                ft.save()
            messages.success(request, "Файл добавлен. Ожидайте письмо с ключем доступа для скачивания",extra_tags="alert-success")
            mess = 'Ваш email:' + ' ' + form_e.instance.email + ' был использован для загрузки файлов.' + \
                    ' Ключ доступа: ' + form_e.instance.slug + '\n' + 'Или перейдите по ссылке: ' + 'http://'+ url_site + '/get-' + form_e.instance.slug
            from_email = form_e.instance.email
            send_mail('Спасибо что выбрали нас!', mess, settings.EMAIL_HOST_USER, [from_email], fail_silently=False)
            return redirect('/')
        else:
            mes += 1
    if mes > 0:
        messages.error(request, "Файл не подходит ни под одно расширение! Разрешенные файлы %s" % f_type, extra_tags="alert-danger")
        return redirect(return_path)
    #return render(request, '../templates/catalog/index.html', args)

def category(request, category_slug):
    args={}
    args['username'] = auth.get_user(request).username
    try:
        args['title'] = Category.objects.get(slug = category_slug)
        args['category'] = Catalog.objects.filter(category=Category.objects.get(slug=category_slug), choices='is_open').order_by('-date_add')
        return render(request, '../templates/catalog/category.html', args)
    except Category.DoesNotExist:
        raise Http404


def view_details(request, slug):
    args={}
    args.update(csrf(request))
    try:
        a=[]
        args['username'] = auth.get_user(request).username
        args['title']=Catalog.objects.get(slug=slug).title
        args['catalog']= Catalog.objects.get(slug=slug, choices='is_open')
        args['files'] = FilesCatalog.objects.filter(catalog=Catalog.objects.get(slug=slug, choices='is_open'))
        for i in args['files']:
            a.append({'file': {'id': i.id, 'name': str(i.files_s).split('/')[3]}})
        args['files_m'] = a
        return render(request, '../templates/catalog/view_details.html', args)
    except Catalog.DoesNotExist:
        raise Http404

# Get LINK
def view_expresfile(request, slug):
    args={}
    args.update(csrf(request))
    try:
        a = []
        args['title'] = ExpresFiles.objects.get(slug=slug).email
        args['expres_file']= ExpresFiles.objects.filter(slug=slug)
        args['files'] = FilesExpres.objects.filter(expresfile_id = ExpresFiles.objects.get(slug=slug))
        for i in args['files']:
            a.append({'file': {'id': i.id, 'name': str(i.files_s).split('/')[3]}})
        args['files_m'] = a
        return render(request, '../templates/catalog/views_expresfile.html', args)
    except ExpresFiles.DoesNotExist:
        raise Http404

# Get KEY
def search_key(request):
    args = {}
    args.update(csrf(request))
    args['form_search_key'] = SearchKey()
    if request.POST:
        g = SearchKey(request.POST)#request.POST.get('search', '')
        if g.is_valid():
            a = []
            try:
                args['title'] = ExpresFiles.objects.get(slug=g.cleaned_data['s_key']).email
                args['expres_file'] = ExpresFiles.objects.filter(slug=g.cleaned_data['s_key'])
                args['files'] = FilesExpres.objects.filter(expresfile_id=ExpresFiles.objects.get(slug=g.cleaned_data['s_key']))
                print(args['files'].count())
                for i in args['files']:
                    a.append({'file':{'id': i.id, 'name': str(i.files_s).split('/')[3]}})
                args['files_m']= a
                return render(request, '../templates/catalog/views_expresfile.html', args)
            except ExpresFiles.DoesNotExist:
                messages.error(request, "Файл с таким ключем не найден!", extra_tags="alert-danger")
                return redirect('/')
        else:
            return redirect('/')
    return render(request, '../templates/catalog/views_expresfile.html', args)

# download file expres
def download_link(request, slug, file_id):
    url_site = request.META['HTTP_HOST']
    try:
        file = FilesExpres.objects.filter(expresfile_id=ExpresFiles.objects.get(slug=slug).id)
        for f in file:
            file_name = (f.files_s.name.split('/')[3]).split('.')[0]
            file_path = os.path.join(f.files_s.path)
            f_type = f.files_s.path.split('.')[-1]
            f_email = ExpresFiles.objects.get(slug=slug).email
            f = open(file_path, 'rb')
            response = HttpResponse(f, content_type='application/force-download')
            response['Content-Disposition'] = 'attachment; filename=%s' % url_site+'_'+ file_name + '.' + f_type
            return response
    except FilesExpres.DoesNotExist:
        raise Http404

# download file catalog
def download_d(request, slug, file_id):
    try:
        url_site = request.META['HTTP_HOST']
        file = FilesCatalog.objects.filter(catalog_id=Catalog.objects.get(slug=slug).id)
        for f in file:
            file_name = (f.files_s.name.split('/')[3]).split('.')[0]
            file_path = os.path.join(f.files_s.path)
            f_type = f.files_s.path.split('.')[-1]
            f_d = Catalog.objects.get(slug=slug)
            f = open(file_path, 'rb')
            response = HttpResponse(f, content_type='application/force-download')
            response['Content-Disposition'] = 'attachment; filename=%s' % url_site+'_'+ file_name + '.' + f_type
            return response
    except FilesCatalog.DoesNotExist:
        raise Http404

def myfiles(request, user_id):
    args={}
    args.update(csrf(request))
    args['username']= auth.get_user(request).username
    if args['username']:
        args['title']= 'Мои файлы'
        args['catalog'] = Catalog.objects.filter(category__is_publish=True, user_id=auth.get_user(request).id).order_by('-date_add')
        return render(request, '../templates/catalog/myfiles.html', args)
    else:
        redirect('/')

def private_files(request, user_id):
    args={}
    args.update(csrf(request))
    args['username']= auth.get_user(request).username
    if args['username']:
        args['title']= 'Личные файлы'
        args['catalog'] = Catalog.objects.filter(category__is_publish=True, user_id=auth.get_user(request).id, choices='is_for_me').order_by('-date_add')
        return render(request, '../templates/catalog/myfiles.html', args)
    else:
        return redirect('/')

def addfile(request):
    args={}
    args.update(csrf(request))
    if auth.get_user(request).username:
        args['username'] = auth.get_user(request).username
        args['title'] = 'Добавить файл'
        args['form_c'] = CatalogForms()
        args['form_f'] = FilesCatalogForms()
        return render(request, '../templates/catalog/addfiles.html', args)
    else:
        return redirect('/')

def get_addfile(request):
    # for count, x in enumerate(request.FILES.getlist('files_s')):
    #     def proces(f):
    #         with open('directory', 'wb+') as destination:
    #             for file in f.chunks():
    #                 destination.write(file)
    #     pass
    args = {}
    url_site = request.META['HTTP_HOST']
    args.update(csrf(request))
    return_path = request.META.get('HTTP_REFERER', '/')
    args['form_c'] = CatalogForms()
    args['form_f'] = FilesCatalogForms()
    if request.POST:
        form_c = CatalogForms(request.POST, request.FILES)
        form_f = FilesCatalogForms(request.FILES)
        if form_c.is_valid():
            form_c.instance.user =request.user
            form_c.save()

templates/catalog/addfiles.html
{% extends 'base.html' %}
{% block script %}
    <script type="text/javascript">
    function OptionsSelectedIsOpen() {
            if (document.getElementById("id_is_open").checked == true){
                document.getElementById("id_is_slug").disabled = true;
                document.getElementById("id_is_for_me").disabled = true;
            }else {
                document.getElementById("id_is_slug").disabled = false;
                document.getElementById("id_is_for_me").disabled = false;
            }

        }
    function OptionsSelectedIsSlug() {
        if (document.getElementById("id_is_slug").checked == true){
            document.getElementById("id_is_open").disabled = true;
            document.getElementById("id_is_for_me").disabled = true;
            }else {
            document.getElementById("id_is_open").disabled = false;
            document.getElementById("id_is_for_me").disabled = false;
        }
        }
    function OptionsSelectedIsForMe() {
            if (document.getElementById("id_is_for_me").checked == true){
                document.getElementById("id_is_slug").disabled = true;
                document.getElementById("id_is_open").disabled = true;
            }else {
                document.getElementById("id_is_slug").disabled = false;
                document.getElementById("id_is_open").disabled = false;
            }
        }
</script>
{% endblock %}
{% block content %}
    <style>
    ul#id_choices{
        list-style: none;
    }
    </style>
    <div class="col-md-6">
        <form action="{% url 'add' %}" method="POST" class="form-horizontal" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form_c.as_p }}
            {{ form_f.as_p }}
            <input type="submit" class="btn btn-primary" value="Сохранить">

        </form>
    </div>
{% endblock %}

templates/catalog/category.html
{% extends 'base.html' %}
{% load static thumbnail%}
<title>{{ title }}</title>
{% block content %}
    <div class="row">
    {% for file in category %}
        {% if file.cover %}
{#        Portret #}
        {% if file.cover|is_portrait %}
            <div class="col-md-3 box col-xs-6">
                <a href="{% url 'details' file.slug %}">

                        <div class="image" id="image">
                            {% thumbnail file.cover "100x150" crop="center" as im%}
                                <img src="{{ im.url }}">
                            {% endthumbnail %}
                        </div>
                <div class="title" id="title"><h5>{{ file.title }}</h5></div>
                </a>
            <div class="category" id="category">{{ category_verbos_name }}: <a href="{% url 'category' file.category.slug %}">{{ file.category }}</a></div>
            </div>

        {% else %}
{#        ------------------------------      #}
        <div class="col-md-3 box col-xs-12">
         <a href="{% url 'details' file.slug %}">
            <div class="image" id="image">
                    {% thumbnail file.cover "250x150" crop="center" as im%}
                        <img src="{{ im.url }}">
                    {% endthumbnail %}
            </div>
                <div class="title" id="title"><h5>{{ file.title }}</h5></div>
         </a>
            <div class="category" id="category">{{ category_verbos_name }}: <a href="{% url 'category' file.category.slug %}">{{ file.category }}</a></div>
        </div>
            {% endif %}
        {% endif %}
    {% endfor %}
    </div>
{% endblock %}

templates/catalog/index.html
{% extends 'base.html' %}
{% load static thumbnail%}
{% block head %}
{% endblock %}

{% block content %}
    {% if not username %}
        <div class="row" style="margin-bottom: 15px">
            <div class="col-md-4"></div>
                <div class="col-md-4 search-key">
                    <form action="{% url 'search_key' %}" role="search" method="POST">
                        {% csrf_token %}
                        <div class="col-md-6 col-xs-8 ">
                            {{ form_search_key}}
                        </div>
                        <div class="col-md-6 col-xs-4">
                            <input type="submit" class="btn bg-primary" value="Найти">
                        </div>
                    </form>
                </div>
            <div class="col-md-4"></div>
        </div>
        <div class="row">
            <div id="wrapper">
                <main class="main-wrapper">
                    <div id="second">
                    <h3>Загрузить временный файл</h3>
                        <div>
                            <form action="{% url 'addfile' %}" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ expres_form.as_p }}
                                {{ files_expres.as_p }}
                                <input type="submit" class="btn bg-primary" value="Загрузить">
                            </form>
                        </div>
                    </div>
                </main>
            </div>
        </div>
    {% endif %}
    <div class="row">
    {% for file in catalog %}
    {% if file.cover %}
{#        Portret #}
        {% if file.cover|is_portrait %}
            <div class="col-md-3 box col-xs-6">
                <a href="{% url 'details' file.slug %}">

                        <div class="image" id="image">
                            {% thumbnail file.cover "100x150" crop="center" as im%}
                                <img src="{{ im.url }}">
                            {% endthumbnail %}
                        </div>
                <div class="title" id="title"><h5>{{ file.title }}</h5></div>
                </a>
            <div class="category" id="category">{{ category_verbos_name }}: <a href="{% url 'category' file.category.slug %}">{{ file.category }}</a></div>
            </div>

        {% else %}
{#        ------------------------------      #}
        <div class="col-md-3 box col-xs-12">
         <a href="{% url 'details' file.slug %}">
            <div class="image" id="image">
                    {% thumbnail file.cover "250x150" crop="center" as im%}
                        <img src="{{ im.url }}">
                    {% endthumbnail %}
            </div>
                <div class="title" id="title"><h5>{{ file.title }}</h5></div>
         </a>
            <div class="category" id="category">{{ category_verbos_name }}: <a href="{% url 'category' file.category.slug %}">{{ file.category }}</a></div>
        </div>
            {% endif %}
        {% endif %}
    {% endfor %}
    </div>


{% endblock %}

templates/catalog/myfiles.html
{% extends 'base.html' %}
{% block content %}
{% for file in catalog %}
    {% if file.is_open %}
        <div class="col-md-3 box">
        <a href="{% url 'details' file.slug %}">
            {% if file.cover %}
                {% load static thumbnail%}
                <div class="image" id="image">
                     {% if file.cover|is_portrait %}
                    {% thumbnail file.cover "100x150" crop="center" as im%}
                        <img src="{{ im.url }}">
                    {% endthumbnail %}
                {% else %}
                     {% thumbnail file.cover "250x150" crop="center" as im%}
                        <img src="{{ im.url }}">
                    {% endthumbnail %}
                {% endif %}
                </div>
            {% endif %}
        <div class="title" id="title"><h5>{{ file.title }}</h5></div>
        </a>

            <div class="category" id="category">{{ category_verbos_name }}: <a href="{% url 'category' file.category.slug %}">{{ file.category }}</a></div>
            <div class="row">
            <div class="col-md-6"><a href="#">Редактировать</a></div>
            <div class="col-md-6"><a href="#">Удалить</a></div>
            </div>
        </div>
        {% else %}
         <div class="col-md-3 box">
        <a href="{% url 'details_slug' file.slug %}">
            {% if file.cover %}
                {% load static thumbnail%}
                <div class="image" id="image">
                     {% if file.cover|is_portrait %}
                    {% thumbnail file.cover "100x150" crop="center" as im%}
                        <img src="{{ im.url }}">
                    {% endthumbnail %}
                {% else %}
                     {% thumbnail file.cover "250x150" crop="center" as im%}
                        <img src="{{ im.url }}">
                    {% endthumbnail %}
                {% endif %}
                </div>
            {% endif %}
        <div class="title" id="title"><h5>{{ file.title }}</h5></div>
        </a>

            <div class="category" id="category">{{ category_verbos_name }}: <a href="{% url 'category' file.category.slug %}">{{ file.category }}</a></div>
            <div class="row">
            <div class="col-md-6"><a href="#">Редактировать</a></div>
            <div class="col-md-6"><a href="#">Удалить</a></div>
            </div>
        </div>
    {% endif %}
    {% endfor %}
{% endblock %}

templates/catalog/search_result.html
{% extends 'base.html' %}
{% load static thumbnail%}
{% block content %}
    {{ query_string }}
    <hr>
    {% for file in found_entries %}
        <div class="row">
        <div class="col-xs-6">
           {% if file.cover %}
{#        Portret #}
            {% if file.cover|is_portrait %}
                <a href="{% url 'details' file.slug %}">
                    <div class="image" id="image">
                        {% thumbnail file.cover "100x150" crop="center" as im%}
                            <img src="{{ im.url }}">
                        {% endthumbnail %}
                    </div>
                </a>
        {% else %}
{#        ------------------------------      #}
         <a href="{% url 'details' file.slug %}">
            <div class="image" id="image">
                {% thumbnail file.cover "250x150" crop="center" as im%}
                    <img src="{{ im.url }}">
                {% endthumbnail %}
            </div>
         </a>
            {% endif %}
        {% endif %}
        </div>
        <div class="col-xs-6">
            <div class="title" id="title"><h5>{{ file.title }}</h5></div>
            <div class="category" id="category">{{ category_verbos_name }}: <a href="{% url 'category' file.category.slug %}">{{ file.category }}</a></div>
            <p>{{ file.description}}</p>
        </div>
        </div>
    {% endfor %}

{% endblock %}

templates/catalog/view_details.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-5">
            {% if catalog.cover %}
                    {% load static thumbnail%}
                    <div class="image" id="image">
                         {% if catalog.cover|is_portrait %}
                        {% thumbnail catalog.cover "200x300" crop="center" as im%}
                            <img src="{{ im.url }}">
                        {% endthumbnail %}
                    {% else %}
                         {% thumbnail catalog.cover "450x300" crop="center" as im%}
                            <img src="{{ im.url }}">
                        {% endthumbnail %}
                    {% endif %}
                    </div>
                {% endif %}
        </div>
        <div class="col-md-7 format-text">
            <h3>{{ catalog.title }}</h3>
            <p>Добавлен: {{ catalog.date_add }}</p>
            <p>{{ category_verbos_name }}: {{ catalog.category }}</p>
            <p>Автор: {{ catalog.user }}</p>
            <p>Описание: <br>{{ catalog.description }}</p>
        </div>
    </div>
    <div class="row">
    <h4>Files</h4>
    <table class="table table-striped table-hover ">
            <thead>
            <tr>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
                {% for i in files_m %}
                    <tr>
                        <td>{{ i.file.name }}</td>
                        <td><a href="{% url 'download_d' catalog.slug i.file.id %}">Скачать файл</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/catalog/views_expresfile.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-6 format-text">
            <div class="blog-post">
        {% for expres in expres_file %}
            <small>{{ expres.date_add }}</small>
            <h4 class="blog-post-title">{{ expres.email }}</h4>

            <p>Описание:</p>
            <p>{{ expres.description }}</p>
            </div>
            </div>

            </div>
            <div class="row">
            <br>
            <table class="table table-striped table-hover ">
            <thead>
            <tr>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
                {% for i in files_m %}
                    <tr>
                        <td>{{ i.file.name }}</td>
                        <td><a href="{% url 'download' expres.slug i.file.id %}">Скачать файл</a></td>
                    </tr>
                {% endfor %}
            </tbody>
            </table>
        {% endfor %}
        </div>
{% endblock %}